### ISSUE TITLE
AppHook Not showing in Application menu

### ISSUE THREAD

**Issue by vaibhav-jain** [bitlabstudio/cmsplugin-image-gallery#12]
Hey i'm using this plugin in one of my project. But this time it is not showing as a `AppHook` in application menu. If you can tell me what might be the reason for it??

**Comment by vaibhav-jain** [comment]
Downgrading the python package(s) version Helped me

**Comment by grrodre** [comment]
The file miss an "s" and it is now showed on the hooks.

cms_app.py  ==> cms_apps.py
